### ISSUE TITLE
[fix] add async keyword to administrator.getServicesConfigurations()

### ISSUE THREAD

**Issue by lgrd** [IGNF/road2#52]
### Need 

The function administrator.getServicesConfigurations() works and it is used inside the admin API. But sometimes, an emtpy answer is returned. 

### Tasks 

- [ ] Fix it 
- [ ] Run tests 
  - [ ] inside docker (rtest)
  - [ ] outside docker : multiple requests to verifiy

**Comment by lgrd** [comment]
@jmkerloch I can't reproduce the bug ^^ do you ? So it seems to work without the async/await stuff. Maybe, we can close this issue and open it later if we find a way to identify it.

**Comment by jmkerloch** [comment]
@lgrd I didn't reproduce this issue on my test.I'm OK to close it. We could re open it if we find a way to reproduce it.
